Refactor exceptions.
AzureAD/microsoft-authentication-library-common-for-objc pull request #1024
Opened 2021-08-10 23:51 UTC by antrix1989

## Proposed changes

Related work item: https://identitydivision.visualstudio.com/Engineering/_workitems/edit/1437512

## Type of change

- [ ] Feature work
- [ ] Bug fix
- [ ] Documentation
- [ ] Engineering change
- [ ] Test
- [ ] Logging/Telemetry

## Risk

- [ ] High – Errors could cause MAJOR regression of many scenarios. (Example: new large features or high level infrastructure changes)
- [ ] Medium – Errors could cause regression of 1 or more scenarios. (Example: somewhat complex bug fixes, small new features)
- [ ] Small – No issues are expected. (Example: Very small bug fixes, string changes, or configuration settings changes)

## Additional information

2021-08-10 23:52 UTC, kaisong1990 commented on IdentityCore/src/MSIDError.h
>  extern NSString * _Nonnull MSIDKeychainErrorDomain;
This pull request does not update changelog.txt.

Please consider if this change would be noticeable to a partner or user and either update changelog.txt or resolve this conversation.
<!-- changelog-comment -->

2021-08-11 21:45 UTC, oldalton requested changes

2021-08-11 21:45 UTC, oldalton commented on IdentityCore/src/util/NSURL+MSIDExtensions.m
> +                @throw MSIDException(MSIDGenericException, @"Port is not a valid integer or port.", nil);
This looks like a potentially breaking change. Possible to use previous exception info?

2021-08-11 21:45 UTC, oldalton commented on IdentityCore/src/validation/MSIDAadAuthorityCache.m
> +            @throw MSIDException(MSIDGenericException, @"Port is not a valid integer or port.", nil);
Same here

2021-08-11 21:58 UTC, oldalton approved these changes

2021-08-11 22:22 UTC, merged