added additional logging and fixed some misplaced logging in default/legacy accessors & credential cache.
AzureAD/microsoft-authentication-library-common-for-objc pull request #1059
Opened 2021-10-29 21:22 UTC by NerevarineRule

## Proposed changes

Trying to add more logging in the legacy & default accessor logic and credential cache logic as well.
By doing so we can better identify how credentials get filtered out by the underlying logic.
Also there were a couple ares where logging was not placed in the correct place. so also fixing that. 

## Type of change

- [ ] Feature work
- [ ] Bug fix
- [ ] Documentation
- [ ] Engineering change
- [ ] Test
- [ ] Logging/Telemetry

## Risk

- [ ] High – Errors could cause MAJOR regression of many scenarios. (Example: new large features or high level infrastructure changes)
- [ ] Medium – Errors could cause regression of 1 or more scenarios. (Example: somewhat complex bug fixes, small new features)
- [ ] Small – No issues are expected. (Example: Very small bug fixes, string changes, or configuration settings changes)

## Additional information

2021-10-29 21:29 UTC, kaisong1990 commented on IdentityCore/src/cache/token/MSIDCredentialCacheItem.m
> +        MSID_LOG_WITH_CTX(MSIDLogLevelInfo, nil, @"(%@) cached item did not have a valid realm. Actual: %@, expected: %@", NSStringFromClass(self.class), self.realm, realm);
Can you double-check if it is ok to use Info level from security perspective?

2021-10-29 21:29 UTC, kaisong1990 approved these changes
Approved with comments

2021-10-29 21:31 UTC, oldalton requested changes
Unfortunately, those logs are too verbose to be info level. Also, please make sure you don't log PII (UPN).

2021-11-05 20:54 UTC, oldalton requested changes
Added a few more questions.

2021-11-05 20:54 UTC, oldalton commented on IdentityCore/src/cache/accessor/MSIDLegacyTokenCacheAccessor.m
> +            MSID_LOG_WITH_CTX_PII(MSIDLogLevelVerbose, context, @"(Legacy accessor) cached home account id mismatches account identifier value. cached: %@, actual: %@",MSID_PII_LOG_TRACKABLE(tokenCac
Please use pre-calculated homeAccountId hash instead.

2021-11-05 20:54 UTC, oldalton commented on IdentityCore/src/cache/accessor/MSIDLegacyTokenCacheAccessor.m
> +            MSID_LOG_WITH_CTX(MSIDLogLevelVerbose, context, @"(Legacy accessor) Credential type is PriamryRefreshToken.");
Typo: PriamryRefreshToken.

2021-11-05 20:54 UTC, oldalton commented on IdentityCore/src/cache/accessor/MSIDLegacyTokenCacheAccessor.m
> +    MSID_LOG_WITH_CTX_PII(MSIDLogLevelInfo, context, @"(Legacy accessor) Get accounts with environment %@, clientId %@, familyId %@, account identifier %@, legacy identifier %@", authority.environmen
Can you clarify why this change is needed?

2021-11-05 20:54 UTC, oldalton commented on IdentityCore/src/cache/accessor/MSIDDefaultTokenCacheAccessor.m
> +    MSID_LOG_WITH_CTX(MSIDLogLevelInfo, context, @"(Default accessor) Found %lu tokens with environment", (unsigned long)[resultTokens count]);
👍

2021-11-05 20:54 UTC, oldalton commented on IdentityCore/src/cache/accessor/MSIDDefaultTokenCacheAccessor.m
> +    MSID_LOG_WITH_CTX(MSIDLogLevelInfo, context, @"(Default accessor) Found %lu cached credentials", (unsigned long)[cacheItems count]);
Is this needed? We already log number below at line 1034.

2021-11-05 20:54 UTC, oldalton commented on IdentityCore/src/cache/accessor/MSIDDefaultTokenCacheAccessor.m
> +        MSID_LOG_WITH_CTX(MSIDLogLevelVerbose, context, @"(Default accessor) found %ld accounts with legacy account id. returning first account.",accountCacheItems.count);
nit: should you cast accountCacheItems.count?

2021-11-05 20:54 UTC, oldalton commented on IdentityCore/src/cache/accessor/MSIDDefaultTokenCacheAccessor.m
> +    MSID_LOG_WITH_CTX(MSIDLogLevelInfo, context, @"(Default accessor) querying account with legacy account id");
Does this give enough extra information to justify info-level log?

2021-11-05 20:54 UTC, oldalton commented on IdentityCore/src/cache/accessor/MSIDDefaultTokenCacheAccessor.m
> +    MSID_LOG_WITH_CTX(MSIDLogLevelVerbose, context, @"(Default accessor) %ld accounts found with account identifier and authority.",accountCacheItems.count);
Do you need to cast accountCacheItems.count here?

2021-11-05 20:54 UTC, oldalton commented on IdentityCore/src/cache/accessor/MSIDDefaultTokenCacheAccessor.m
> +    MSID_LOG_WITH_CTX(MSIDLogLevelInfo, context, @"(Default accessor) number of filtered (no-return) accounts: %ld.",noReturnAccountUPNSet.count);
Does this need to be info-level?

2021-11-05 20:54 UTC, oldalton commented on IdentityCore/src/cache/accessor/MSIDDefaultTokenCacheAccessor.m
> +        MSID_LOG_WITH_CTX(MSIDLogLevelInfo, context, @"(Default accessor) signedInAccountsOnly Enabled. retrieve account IDs from RT.");
Does this need to be info level?

2022-01-08 05:36 UTC, oldalton commented
@NerevarineRule, can we close this one or it's still needed?

2022-01-14 19:44 UTC, closed without merging