add new account type adfs
AzureAD/microsoft-authentication-library-common-for-objc pull request #1397
Opened 2024-07-17 17:12 UTC by SunandaChowdhary

## Proposed changes
Update MSIDAccountType enum to include "ADFS" as new account type. Correspondingly update implementation as well

Describe what this PR is trying to do.
When ADFS account type is presented to Identity Core then it is defaulted to type "Other" causing ADFS on prem flow to fail for Outlook macOS. Hence added "adfs" account type.

## Type of change

- [ ] Feature work
- [x] Bug fix
- [ ] Documentation
- [ ] Engineering change
- [ ] Test
- [ ] Logging/Telemetry

## Risk
Migration of existing ADFS accounts will not work. This is expected by OneAuth-MSAL.

- [ ] High – Errors could cause MAJOR regression of many scenarios. (Example: new large features or high level infrastructure changes)
- [ ] Medium – Errors could cause regression of 1 or more scenarios. (Example: somewhat complex bug fixes, small new features)
- [x] Small – No issues are expected. (Example: Very small bug fixes, string changes, or configuration settings changes)

## Additional information

2024-07-17 17:20 UTC, SunandaChowdhary commented on IdentityCore/src/oauth2/account/MSIDAccountType.h
>      MSIDAccountTypeOther,
@ameyapat does this change warrants a changelog entry? What is the guideline for such changes?

2024-07-17 19:09 UTC, swasti29 approved these changes
The change will break account cache schema for previously cached account of type ADFS, but this is acceptabled and expected by OneAuth.
Please test end to end.

2024-07-17 20:41 UTC, ameyapat requested changes
For hotfix, please cherry pick changes on a new branch and open a new PR against hotfix/1.7.37

2024-07-17 22:37 UTC, juan-arias commented on IdentityCore/src/oauth2/account/MSIDAccountType.m
> +			  @"adfs": @(MSIDAccountTypeADFS)};
nit: fix the identation 
```suggestion
                          @"adfs": @(MSIDAccountTypeADFS)};
```

2024-07-17 22:39 UTC, juan-arias commented on changelog.txt
> -* Update device register to include a new hint for token protection (#1394)
These other changelogs shouldn't be removed

2024-07-18 01:57 UTC, closed without merging

2024-07-18 01:57 UTC, SunandaChowdhary commented
Merged directly to hotfix branch