Add pii around upn for wp registration web response
AzureAD/microsoft-authentication-library-common-for-objc pull request #1444
Opened 2024-11-15 00:59 UTC by kaisong1990

## Proposed changes

Add PII around upn

## Type of change

- [ ] Feature work
- [x] Bug fix
- [ ] Documentation
- [ ] Engineering change
- [ ] Test
- [ ] Logging/Telemetry

## Risk

- [ ] High – Errors could cause MAJOR regression of many scenarios. (Example: new large features or high level infrastructure changes)
- [ ] Medium – Errors could cause regression of 1 or more scenarios. (Example: somewhat complex bug fixes, small new features)
- [ ] Small – No issues are expected. (Example: Very small bug fixes, string changes, or configuration settings changes)

## Additional information

2024-11-15 01:02 UTC, oldalton requested changes
We shouldn't use _PII_NULLIFY for actual code, since we rely on user info as part of the flow. We should only do _PII_NULLIFY in logs

2024-11-15 19:05 UTC, kaisong1990 commented
Hi @oldalton do we need to check into this release or if we can wait till the next one?

2024-11-22 18:55 UTC, kaisong1990 commented
> We shouldn't use _PII_NULLIFY for actual code, since we rely on user info as part of the flow. We should only do _PII_NULLIFY in logs

Hi @oldalton I' benchmarked the performance and the difference is below 1 ms. The NSRange solution is slightly better and it is currently used in `MSIDMaskedUsernameLogParameter` so I switched with the similar logic

2025-05-27 22:23 UTC, swasti29 commented
@kaisong1990  Please close the PR if not valid anymore.

2025-06-06 00:37 UTC, closed without merging