Adding a BOOL property in request parameters
AzureAD/microsoft-authentication-library-common-for-objc pull request #989
Opened 2021-05-03 20:26 UTC by ameyapat

## Proposed changes

Adding a BOOL property in request parameters that will indicate if the request was initiated from within SSO extension.
Since the parameters are initially read from info plist, this property will read as true only from targets in broker project which are for SSO extension. Related broker PR : https://github.com/AzureAD/azure-activedirectory-tokenbroker-for-objc/pull/726 

## Type of change

- [x] Feature work
- [ ] Bug fix
- [ ] Documentation
- [ ] Engineering change
- [ ] Test
- [ ] Logging/Telemetry

## Risk

- [ ] High – Errors could cause MAJOR regression of many scenarios. (Example: new large features or high level infrastructure changes)
- [ ] Medium – Errors could cause regression of 1 or more scenarios. (Example: somewhat complex bug fixes, small new features)
- [x] Small – No issues are expected. (Example: Very small bug fixes, string changes, or configuration settings changes)

## Additional information

2021-05-03 20:27 UTC, kaisong1990 commented on IdentityCore/src/parameters/MSIDRequestParameters.h
>  @property (nonatomic) NSString *intuneApplicationIdentifier;
This pull request does not update changelog.txt.

Please consider if this change would be noticeable to a partner or user and either update changelog.txt or resolve this conversation.
<!-- changelog-comment -->

2021-05-04 02:44 UTC, oldalton requested changes

2021-05-04 02:44 UTC, oldalton commented on IdentityCore/src/parameters/MSIDRequestParameters.h
> +@property (nonatomic,readonly) BOOL isFromSSOExtension;
Added a comment in broker repo as well, but I think parameters is not the best place for this flag. Better to have it in constructor of the controller or not have it at all.

2021-05-04 21:04 UTC, ameyapat commented
Closing PR as the property won't be used anymore

2021-05-04 21:04 UTC, closed without merging